### PR TITLE
Resolves #65, corrects issue with Matching question response

### LINKED ISSUE #65: Matching question response is incorrect
For matching questions, the result.response property uses a target id that is not one of the listed targets. The correctResponsesPattern does use the right id. Example (redacted to remove client information) object and result properties from a statement below. 

I can't figure out where in the code the definition for statements (e.g. the correctResponsesPattern is getting built)

```
"object": {
    "objectType": "Activity",
    "id": "https://example.com/url",
    "definition": {
      "name": {
        "en": "Foo"
      },
      "description": {
        "en": "Lorem foobar"
      },
      "type": "http://adlnet.gov/expapi/activities/question",
      "interactionType": "matching",
      "correctResponsesPattern": [
        "1[.]1_1"
      ],
      "source": [
        {
          "id": "1",
          "description": {
            "en": "Thing to match to..."
          }
        }
      ],
      "target": [
        {
          "id": "1_1",
          "description": {
            "en": "This other thing"
          }
        },
        {
          "id": "1_2",
          "description": {
            "en": "Or this one"
          }
        }
      ]
    }
  },
  "result": {
    "score": {
      "raw": 1
    },
    "success": true,
    "completion": true,
    "response": "1[.]1"
  }```

### PR DESCRIPTION
**Pull request by brian-learningpool**
The response is now in a format consitent with correctResponsesPattern.

### CODE REVIEW

File: js/adapt-contrib-xapi.js [hunk 1]
```diff
@@ -626,9 +626,12 @@ define([
           break;
         }
         case 'matching': {
-          response = response.replace(/#/g, "[,]");
-          response = response.replace(/\./g, "[.]");
-
+          response = response
```
Comment (moloko) [inline js/adapt-contrib-xapi.js]: might be useful to give an example of what the conversion is doing so that it's not necessary to parse the code to figure it out?
