### PR TITLE
Fix: Make sendState call async (Issue/134)

### LINKED ISSUE #134: sendState should behave asynchronously
### Subject of the issue/enhancement/features
We have a custom plugin that forces submit of multiple components in one functional batch
(In essence:
```
_.each(largeArrayOfComponentViews, (componentView) => {
        componentView.onSubmitClicked();
      });
```
)

When it comes to handling a large volume of components, we have found that this effectively creates a race condition and the state that comes back may actually not be the last state sent, thus cutting off some question values when the state is loaded again on subsequent views.

I believe setting an await on https://github.com/adaptlearning/adapt-contrib-xapi/blob/master/js/XAPI.js#L1082 should help us out in this regard

### PR DESCRIPTION
**Pull request by cahirodoherty-learningpool**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes #134 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Apply debounce around sendState calls to avoid concurrency issues

### CODE REVIEW

File: js/XAPI.js [hunk 1]
```diff
@@ -65,6 +65,8 @@ class XAPI extends Backbone.Model {
       components: 'component',
       offlineStorage: 'offlineStorage'
     };
+
+    this.sendState = _.debounce(this.sendState.bind(this), 500);
```
Comment (oliverfoster) [inline js/XAPI.js:69]: Sorry, I forgot to articulate a problem with this in my ramblings.

`_.debounce` holds back multiple calls to a function until a given time period has passed, then it calls the function only once, with only the last set of arguments passed into the debounce queue.

I believe `sendState` is doing two things, updating a client side state object and then sending that state object to the server.

If this is the case, the first part of `sendState`, updating the client side state object, cannot be hidden behind a debounce as the function requires every set of arguments sent to perform its client side state object updates. The latter part of the `sendState` function can be debounced, as server updates only need to be sent periodically.

Comment (cahirodoherty-learningpool) [reply js/XAPI.js:69]: Ah very good point, I will amend the code. Thanks

File: js/XAPI.js [hunk 2]
```diff
@@ -1124,14 +1123,16 @@ class XAPI extends Backbone.Model {
       state
     });
 
-    // Pass the new state to the LRS.
-    this.xapiWrapper.sendState(activityId, actor, collectionName, registration, newState, null, null, (error, xhr) => {
-      if (error) {
-        Adapt.trigger('xapi:lrs:sendState:error', error);
-      }
+    // Pass the new state to the LRS, but debounced to limit the server updates to periodic updates
+    _.debounce(() => {
```
Comment (oliverfoster) [inline js/XAPI.js:1127]: The debounce function returns a new function each time, the new function is a debounced version of the original function passed as the first argument, the first argument is not executed at any point. You've used `_.debounce` here as if it were `_.defer`.

You'll need to split `sendState` into two named functions. Debounce the `sendStateToServer` function in `initialize` as you had before - by reassigning the instance function as its debounced version: 

`this.sendStateToServer = _.debounce(this.sendStateToServer.bind(this), 500);`. 

Then call `this.sendStateToServer()` at the end of `sendState`.

File: js/XAPI.js [hunk 3]
```diff
@@ -1125,6 +1124,10 @@ class XAPI extends Backbone.Model {
     });
 
     // Pass the new state to the LRS.
+    this.sendStateToServer(activityId, actor, collectionName, registration, newState);
+  }
+
+  sendStateToServer(activityId, actor, collectionName, registration, newState) {
```
Comment (oliverfoster) [inline js/XAPI.js:1130]: I don't think `activityId`, `actor` and `registration` need to be passed, as they come straight from:

```js
    const activityId = this.get('activityId');
    const actor = this.get('actor');
    const registration = this.get('shouldUseRegistration') === true
      ? this.get('registration')
      : null;
```

The values for `collectionName` and `newState` come from the following parts of Adapt.

The XAPI plugin uses [sendState](https://github.com/adaptlearning/adapt-contrib-xapi/blob/267ecbb3c0bbed395a8284412bb59c9fca351e50/js/setupOfflineStorage.js#L51) and a [fakeModel](https://github.com/adaptlearning/adapt-contrib-xapi/blob/267ecbb3c0bbed395a8284412bb59c9fca351e50/js/setupOfflineStorage.js#L7-L11) as the argument `model` to save offlineStorage stuff.

The core sends actual models with their corresponding state object from [adaptModel.js](https://github.com/adaptlearning/adapt-contrib-core/blob/a1b6c57f8608d0a38ef6918ce3bc9bad6961f580/js/models/adaptModel.js#L235-L239)

The `collectionName` value is derived from the `_type` of the `model` attribute (offlineStorage, component, block, course, menu, page, article) and its corresponding xapi type here:
```js
    const type = model.get('_type');
    const collectionName = _.findKey(this.coreObjects, o => {
      return (o === type || o.indexOf(type) > -1);
    });
```
https://github.com/adaptlearning/adapt-contrib-xapi/blob/267ecbb3c0bbed395a8284412bb59c9fca351e50/js/XAPI.js#L60-L68

The `newState` sent to the server is either a collection of block, article, component or contentObject states or the course or offlineStorage state:
https://github.com/adaptlearning/adapt-contrib-xapi/blob/267ecbb3c0bbed395a8284412bb59c9fca351e50/js/XAPI.js#L1105-L1125

What this means is that debounce cannot happen on the `this.sendStateToServer` function unless the function is passed a list of the changed `collectionNames` since the last call to `this.sendStateToServer`. With a list of changed `collectionNames` it can look up the current state objects from `this.get('state')` and then send to them to the server as a batch of `this.xapiWrapper.sendState` requests.

i.e.

`sendState` should update `this.set({ state })` as it does currently but should also update a list like `this.changedCollectionNames[collectionName] = true;` before it calls the debounced `this.sendStateToServer`. 

`sendStateToServer` should then iterate through the changed collection names, fetching the relevant state from the state object and use both of those variables plus the aforementioned variables (activityId, etc) to send a series of `this.xapiWrapper.sendState` requests.

```js
    const activityId = this.get('activityId');
    const actor = this.get('actor');
    const registration = this.get('shouldUseRegistration') === true
      ? this.get('registration')
      : null;
    const changedCollectionNames = Object.keys(this.changedCollectionNames) // capture only the names
    this.changedCollectionNames = {} // reset for the next round
    for (const collectionName of changeCollectionNames) {
       const newState = this.get('state')[collectionName];
       await new Promise(resolve => {
  this.xapiWrapper.sendState(activityId, actor, collectionName, registration, newState, null, null, (error, xhr) => {
           if (error) {
             Adapt.trigger('xapi:lrs:sendState:error', error);
             return resolve(); // as the error is handled by event we shouldn't send it back in the promise
           }
           Adapt.trigger('xapi:lrs:sendState:success', newState);
           return resolve();
        });
      });
    }
```
The function should not be passed

File: js/XAPI.js [hunk 4]
```diff
@@ -1118,23 +1115,41 @@ class XAPI extends Backbone.Model {
     }
 
     // Update the locally held state.
+    this.changedCollectionNames.push(collectionName);
```
Comment (oliverfoster) [inline js/XAPI.js]: The reason I used an object rather than an array, is that with an array and your submit button example, would you have multiple 'component' entries, whereas with a `changed[collectionName] = true` and `Object.keys(changed)`, you get a unique list of changed items.

You only need to send the state update to the server once for each type.

**Review by oliverfoster — APPROVED** [review]
Looks good. Does it work?

File: js/XAPI.js [hunk 5]
```diff
@@ -1516,9 +1532,7 @@ class XAPI extends Backbone.Model {
    * @param {ADL.XAPIStatement[]} statements - An array of valid ADL.XAPIStatement objects.
    */
   async sendStatements(statements) {
-    if (!statements || statements.length === 0) {
-      return;
-    }
+    if (!statements || statements.length === 0) return;
```
Comment (oliverfoster) [inline js/XAPI.js:1535]:
```suggestion
    if (!statements?.length) return;
```
